# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_device_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_device_info.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17proto_device_info.proto\"\x87\x02\n\x0cProtoRuntime\x12\x0f\n\x07up_time\x18\x01 \x01(\r\x12\x18\n\x10message_counters\x18\x02 \x03(\r\x12\x17\n\x0fmcu_temperature\x18\x03 \x01(\x11\x12\x1b\n\x13min_battery_voltage\x18\x04 \x01(\r\x12#\n\x1bmin_battery_mcu_temperature\x18\x05 \x01(\x11\x12\x1f\n\x17\x62\x61ttery_reset_timestamp\x18\x06 \x01(\r\x12\x1b\n\x13max_mcu_temperature\x18\x07 \x01(\x11\x12\x1b\n\x13min_mcu_temperature\x18\x08 \x01(\x11\x12\x16\n\x0eruntime_errors\x18\t \x03(\r\":\n\nProtoModem\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.ModemType\x12\x12\n\nparameters\x18\x02 \x03(\x11\"\xf9\x01\n\x0fProtoDeviceInfo\x12\x12\n\nserial_num\x18\x01 \x01(\x0c\x12\x12\n\nsw_version\x18\x03 \x01(\r\x12#\n\x0cruntime_info\x18\r \x01(\x0b\x32\r.ProtoRuntime\x12\x1a\n\x05modem\x18\x0e \x01(\x0b\x32\x0b.ProtoModem\x12\x11\n\tcommit_id\x18\x0f \x01(\t\x12\x13\n\x0b\x63loud_token\x18\x10 \x01(\t\x12\x19\n\x11memory_statistics\x18\x11 \x03(\rJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\n\x10\x0bJ\x04\x08\x0b\x10\x0cJ\x04\x08\x0c\x10\r*S\n\tModemType\x12\x1a\n\x16MODEM_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fMODEM_TYPE_BC66\x10\x01\x12\x15\n\x11MODEM_TYPE_BC66NA\x10\x02\x62\x06proto3'
)

_MODEMTYPE = _descriptor.EnumDescriptor(
  name='ModemType',
  full_name='ModemType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODEM_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEM_TYPE_BC66', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEM_TYPE_BC66NA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=605,
  serialized_end=688,
)
_sym_db.RegisterEnumDescriptor(_MODEMTYPE)

ModemType = enum_type_wrapper.EnumTypeWrapper(_MODEMTYPE)
MODEM_TYPE_UNSPECIFIED = 0
MODEM_TYPE_BC66 = 1
MODEM_TYPE_BC66NA = 2



_PROTORUNTIME = _descriptor.Descriptor(
  name='ProtoRuntime',
  full_name='ProtoRuntime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='up_time', full_name='ProtoRuntime.up_time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_counters', full_name='ProtoRuntime.message_counters', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mcu_temperature', full_name='ProtoRuntime.mcu_temperature', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_battery_voltage', full_name='ProtoRuntime.min_battery_voltage', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_battery_mcu_temperature', full_name='ProtoRuntime.min_battery_mcu_temperature', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_reset_timestamp', full_name='ProtoRuntime.battery_reset_timestamp', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_mcu_temperature', full_name='ProtoRuntime.max_mcu_temperature', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_mcu_temperature', full_name='ProtoRuntime.min_mcu_temperature', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime_errors', full_name='ProtoRuntime.runtime_errors', index=8,
      number=9, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=291,
)


_PROTOMODEM = _descriptor.Descriptor(
  name='ProtoModem',
  full_name='ProtoModem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ProtoModem.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='ProtoModem.parameters', index=1,
      number=2, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=351,
)


_PROTODEVICEINFO = _descriptor.Descriptor(
  name='ProtoDeviceInfo',
  full_name='ProtoDeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial_num', full_name='ProtoDeviceInfo.serial_num', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sw_version', full_name='ProtoDeviceInfo.sw_version', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime_info', full_name='ProtoDeviceInfo.runtime_info', index=2,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modem', full_name='ProtoDeviceInfo.modem', index=3,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commit_id', full_name='ProtoDeviceInfo.commit_id', index=4,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_token', full_name='ProtoDeviceInfo.cloud_token', index=5,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory_statistics', full_name='ProtoDeviceInfo.memory_statistics', index=6,
      number=17, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=603,
)

_PROTOMODEM.fields_by_name['type'].enum_type = _MODEMTYPE
_PROTODEVICEINFO.fields_by_name['runtime_info'].message_type = _PROTORUNTIME
_PROTODEVICEINFO.fields_by_name['modem'].message_type = _PROTOMODEM
DESCRIPTOR.message_types_by_name['ProtoRuntime'] = _PROTORUNTIME
DESCRIPTOR.message_types_by_name['ProtoModem'] = _PROTOMODEM
DESCRIPTOR.message_types_by_name['ProtoDeviceInfo'] = _PROTODEVICEINFO
DESCRIPTOR.enum_types_by_name['ModemType'] = _MODEMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoRuntime = _reflection.GeneratedProtocolMessageType('ProtoRuntime', (_message.Message,), {
  'DESCRIPTOR' : _PROTORUNTIME,
  '__module__' : 'proto_device_info_pb2'
  # @@protoc_insertion_point(class_scope:ProtoRuntime)
  })
_sym_db.RegisterMessage(ProtoRuntime)

ProtoModem = _reflection.GeneratedProtocolMessageType('ProtoModem', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMODEM,
  '__module__' : 'proto_device_info_pb2'
  # @@protoc_insertion_point(class_scope:ProtoModem)
  })
_sym_db.RegisterMessage(ProtoModem)

ProtoDeviceInfo = _reflection.GeneratedProtocolMessageType('ProtoDeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROTODEVICEINFO,
  '__module__' : 'proto_device_info_pb2'
  # @@protoc_insertion_point(class_scope:ProtoDeviceInfo)
  })
_sym_db.RegisterMessage(ProtoDeviceInfo)


# @@protoc_insertion_point(module_scope)
