# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_measurement_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto_measurement_types.proto*\xf5\x08\n\x0fMeasurementType\x12\x1e\n\x1aMEASUREMENT_TYPE_NO_SENSOR\x10\x00\x12 \n\x1cMEASUREMENT_TYPE_TEMPERATURE\x10\x01\x12\x1d\n\x19MEASUREMENT_TYPE_HUMIDITY\x10\x02\x12)\n%MEASUREMENT_TYPE_ATMOSPHERIC_PRESSURE\x10\x03\x12*\n&MEASUREMENT_TYPE_DIFFERENTIAL_PRESSURE\x10\x04\x12\x1d\n\x19MEASUREMENT_TYPE_OK_ALARM\x10\x05\x12\x18\n\x14MEASUREMENT_TYPE_IAQ\x10\x06\x12\x1d\n\x19MEASUREMENT_TYPE_FLOODING\x10\x07\x12\x1e\n\x1aMEASUREMENT_TYPE_PULSE_CNT\x10\x08\x12&\n\"MEASUREMENT_TYPE_ELECTRICITY_METER\x10\t\x12 \n\x1cMEASUREMENT_TYPE_WATER_METER\x10\n\x12\"\n\x1eMEASUREMENT_TYPE_SOIL_MOISTURE\x10\x0b\x12\x1b\n\x17MEASUREMENT_TYPE_CO_GAS\x10\x0c\x12\x1c\n\x18MEASUREMENT_TYPE_NO2_GAS\x10\r\x12\x1c\n\x18MEASUREMENT_TYPE_H2S_GAS\x10\x0e\x12\"\n\x1eMEASUREMENT_TYPE_AMBIENT_LIGHT\x10\x0f\x12\x1b\n\x17MEASUREMENT_TYPE_PM_1_0\x10\x10\x12\x1b\n\x17MEASUREMENT_TYPE_PM_2_5\x10\x11\x12\x1c\n\x18MEASUREMENT_TYPE_PM_10_0\x10\x12\x12 \n\x1cMEASUREMENT_TYPE_NOISE_LEVEL\x10\x13\x12\x1c\n\x18MEASUREMENT_TYPE_NH3_GAS\x10\x14\x12\x1c\n\x18MEASUREMENT_TYPE_CH4_GAS\x10\x15\x12\"\n\x1eMEASUREMENT_TYPE_HIGH_PRESSURE\x10\x16\x12 \n\x1cMEASUREMENT_TYPE_DISTANCE_MM\x10\x17\x12*\n&MEASUREMENT_TYPE_WATER_METER_ACC_MINOR\x10\x18\x12*\n&MEASUREMENT_TYPE_WATER_METER_ACC_MAJOR\x10\x19\x12\x1c\n\x18MEASUREMENT_TYPE_CO2_GAS\x10\x1a\x12&\n\"MEASUREMENT_TYPE_HUMIDITY_ACCURATE\x10\x1b\x12\x1f\n\x1bMEASUREMENT_TYPE_STATIC_IAQ\x10\x1c\x12#\n\x1fMEASUREMENT_TYPE_CO2_EQUIVALENT\x10\x1d\x12\x1f\n\x1bMEASUREMENT_TYPE_BREATH_VOC\x10\x1e\x12%\n!MEASUREMENT_TYPE_CELLULAR_GATEWAY\x10\x1f\x12\x1f\n\x1bMEASUREMENT_TYPE_PERCENTAGE\x10 b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_measurement_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEASUREMENTTYPE._serialized_start=34
  _MEASUREMENTTYPE._serialized_end=1175
# @@protoc_insertion_point(module_scope)
