# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_device_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_device_info.proto\"\x87\x02\n\x0cProtoRuntime\x12\x0f\n\x07up_time\x18\x01 \x01(\r\x12\x18\n\x10message_counters\x18\x02 \x03(\r\x12\x17\n\x0fmcu_temperature\x18\x03 \x01(\x11\x12\x1b\n\x13min_battery_voltage\x18\x04 \x01(\r\x12#\n\x1bmin_battery_mcu_temperature\x18\x05 \x01(\x11\x12\x1f\n\x17\x62\x61ttery_reset_timestamp\x18\x06 \x01(\r\x12\x1b\n\x13max_mcu_temperature\x18\x07 \x01(\x11\x12\x1b\n\x13min_mcu_temperature\x18\x08 \x01(\x11\x12\x16\n\x0eruntime_errors\x18\t \x03(\r\":\n\nProtoModem\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.ModemType\x12\x12\n\nparameters\x18\x02 \x03(\x11\"4\n\x0fProtoUpdateInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\r\"\xa5\x02\n\x0fProtoDeviceInfo\x12\x12\n\nserial_num\x18\x01 \x01(\x0c\x12\x12\n\nsw_version\x18\x03 \x01(\r\x12#\n\x0cruntime_info\x18\r \x01(\x0b\x32\r.ProtoRuntime\x12\x1a\n\x05modem\x18\x0e \x01(\x0b\x32\x0b.ProtoModem\x12\x11\n\tcommit_id\x18\x0f \x01(\t\x12\x13\n\x0b\x63loud_token\x18\x10 \x01(\t\x12\x19\n\x11memory_statistics\x18\x11 \x03(\r\x12*\n\x10last_update_info\x18\x12 \x01(\x0b\x32\x10.ProtoUpdateInfoJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\n\x10\x0bJ\x04\x08\x0b\x10\x0cJ\x04\x08\x0c\x10\r*S\n\tModemType\x12\x1a\n\x16MODEM_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fMODEM_TYPE_BC66\x10\x01\x12\x15\n\x11MODEM_TYPE_BC66NA\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_device_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEMTYPE._serialized_start=703
  _MODEMTYPE._serialized_end=786
  _PROTORUNTIME._serialized_start=28
  _PROTORUNTIME._serialized_end=291
  _PROTOMODEM._serialized_start=293
  _PROTOMODEM._serialized_end=351
  _PROTOUPDATEINFO._serialized_start=353
  _PROTOUPDATEINFO._serialized_end=405
  _PROTODEVICEINFO._serialized_start=408
  _PROTODEVICEINFO._serialized_end=701
# @@protoc_insertion_point(module_scope)
