# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.proto_measurement_types_pb2 as proto__measurement__types__pb2
import protobuf.proto_rule_pb2 as proto__rule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto_config.proto\x1a\x1dproto_measurement_types.proto\x1a\x10proto_rule.proto\"\x91\x08\n\x0bProtoConfig\x12\x1f\n\x17measurement_period_base\x18\x02 \x01(\r\x12!\n\x19measurement_period_factor\x18\x1a \x01(\r\x12\x1d\n\x15transmission_interval\x18\x03 \x01(\r\x12\x18\n\x10\x62le_turnoff_time\x18\x04 \x01(\r\x12\x14\n\x0c\x61\x63k_interval\x18\x05 \x01(\r\x12\x1b\n\x13request_device_info\x18\x06 \x01(\x08\x12\x19\n\x11request_fw_update\x18\x07 \x01(\x08\x12\x14\n\x0c\x63urrent_time\x18\x08 \x01(\r\x12\x16\n\x0etransfer_limit\x18\t \x01(\r\x12\x1c\n\x14transfer_limit_timer\x18\n \x01(\r\x12\x16\n\x0e\x64\x61ta_server_ip\x18\x0b \x01(\t\x12\x18\n\x10\x64\x61ta_server_port\x18\x0c \x01(\r\x12\x18\n\x10update_server_ip\x18\r \x01(\t\x12\x1e\n\x16update_server_port_udp\x18\x0e \x01(\r\x12\x1f\n\x17update_server_port_coap\x18\x0f \x01(\r\x12\x0b\n\x03\x61pn\x18\x10 \x01(\t\x12\x16\n\x0eplmn_selection\x18\x11 \x01(\r\x12\x1d\n\x15\x64isable_modem_request\x18\x12 \x01(\r\x12\x1d\n\x15request_configuration\x18\x13 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x14 \x03(\r\x12\x0c\n\x04hash\x18\x15 \x01(\r\x12\x1e\n\x16\x61\x63\x63\x65pt_without_testing\x18\x16 \x01(\x08\x12\x1a\n\x12\x63loud_token_config\x18\x17 \x01(\r\x12\x13\n\x0b\x63loud_token\x18\x18 \x01(\t\x12\x15\n\rserial_number\x18\x19 \x01(\x0c\x12\'\n\rchannel_types\x18\x1b \x03(\x0e\x32\x10.MeasurementType\x12\x19\n\x05rules\x18\x1c \x03(\x0b\x32\n.ProtoRule\x12\x1a\n\x12supervision_period\x18\x1d \x01(\r\x12\x1c\n\x14memory_reset_request\x18\x1e \x01(\x08\x12\x18\n\x10modem_bands_mask\x18\x1f \x01(\r\x12\x15\n\rdata_endpoint\x18  \x01(\t\x12\x1e\n\x16\x63onfiguration_endpoint\x18! \x01(\t\x12\x1c\n\x14\x64\x65vice_info_endpoint\x18\" \x01(\t\x12\x15\n\rtime_endpoint\x18# \x01(\t\x12\x1a\n\x12\x62le_tx_power_level\x18$ \x01(\r\x12$\n\x1crequest_runtime_errors_clear\x18% \x01(\x08\x12\x17\n\x0f\x65rror_timestamp\x18& \x01(\r\x12\x16\n\x0ehash_timestamp\x18\' \x01(\rb\x06proto3'
  ,
  dependencies=[proto__measurement__types__pb2.DESCRIPTOR,proto__rule__pb2.DESCRIPTOR,])




_PROTOCONFIG = _descriptor.Descriptor(
  name='ProtoConfig',
  full_name='ProtoConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurement_period_base', full_name='ProtoConfig.measurement_period_base', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurement_period_factor', full_name='ProtoConfig.measurement_period_factor', index=1,
      number=26, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transmission_interval', full_name='ProtoConfig.transmission_interval', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ble_turnoff_time', full_name='ProtoConfig.ble_turnoff_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack_interval', full_name='ProtoConfig.ack_interval', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_device_info', full_name='ProtoConfig.request_device_info', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_fw_update', full_name='ProtoConfig.request_fw_update', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_time', full_name='ProtoConfig.current_time', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transfer_limit', full_name='ProtoConfig.transfer_limit', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transfer_limit_timer', full_name='ProtoConfig.transfer_limit_timer', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_server_ip', full_name='ProtoConfig.data_server_ip', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_server_port', full_name='ProtoConfig.data_server_port', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_server_ip', full_name='ProtoConfig.update_server_ip', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_server_port_udp', full_name='ProtoConfig.update_server_port_udp', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_server_port_coap', full_name='ProtoConfig.update_server_port_coap', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apn', full_name='ProtoConfig.apn', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plmn_selection', full_name='ProtoConfig.plmn_selection', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disable_modem_request', full_name='ProtoConfig.disable_modem_request', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_configuration', full_name='ProtoConfig.request_configuration', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errors', full_name='ProtoConfig.errors', index=19,
      number=20, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='ProtoConfig.hash', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accept_without_testing', full_name='ProtoConfig.accept_without_testing', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_token_config', full_name='ProtoConfig.cloud_token_config', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_token', full_name='ProtoConfig.cloud_token', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='ProtoConfig.serial_number', index=24,
      number=25, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_types', full_name='ProtoConfig.channel_types', index=25,
      number=27, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rules', full_name='ProtoConfig.rules', index=26,
      number=28, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='supervision_period', full_name='ProtoConfig.supervision_period', index=27,
      number=29, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory_reset_request', full_name='ProtoConfig.memory_reset_request', index=28,
      number=30, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modem_bands_mask', full_name='ProtoConfig.modem_bands_mask', index=29,
      number=31, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_endpoint', full_name='ProtoConfig.data_endpoint', index=30,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configuration_endpoint', full_name='ProtoConfig.configuration_endpoint', index=31,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_info_endpoint', full_name='ProtoConfig.device_info_endpoint', index=32,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_endpoint', full_name='ProtoConfig.time_endpoint', index=33,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ble_tx_power_level', full_name='ProtoConfig.ble_tx_power_level', index=34,
      number=36, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_runtime_errors_clear', full_name='ProtoConfig.request_runtime_errors_clear', index=35,
      number=37, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_timestamp', full_name='ProtoConfig.error_timestamp', index=36,
      number=38, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash_timestamp', full_name='ProtoConfig.hash_timestamp', index=37,
      number=39, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=1113,
)

_PROTOCONFIG.fields_by_name['channel_types'].enum_type = proto__measurement__types__pb2._MEASUREMENTTYPE
_PROTOCONFIG.fields_by_name['rules'].message_type = proto__rule__pb2._PROTORULE
DESCRIPTOR.message_types_by_name['ProtoConfig'] = _PROTOCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoConfig = _reflection.GeneratedProtocolMessageType('ProtoConfig', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCONFIG,
  '__module__' : 'proto_config_pb2'
  # @@protoc_insertion_point(class_scope:ProtoConfig)
  })
_sym_db.RegisterMessage(ProtoConfig)


# @@protoc_insertion_point(module_scope)
