# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_measurements.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.proto_measurement_types_pb2 as proto__measurement__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_measurements.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18proto_measurements.proto\x1a\x1dproto_measurement_types.proto\"\x84\x01\n\x0cProtoChannel\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.MeasurementType\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x12\x13\n\x0bstart_point\x18\x04 \x01(\x11\x12\x1a\n\x0esample_offsets\x18\x05 \x03(\x11\x42\x02\x10\x01J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\t\"\x8e\x02\n\x11ProtoMeasurements\x12\x12\n\nserial_num\x18\x01 \x01(\x0c\x12\x16\n\x0e\x62\x61ttery_status\x18\x02 \x01(\x08\x12\x1f\n\x17measurement_period_base\x18\x03 \x01(\r\x12!\n\x19measurement_period_factor\x18\x08 \x01(\r\x12\x1f\n\x08\x63hannels\x18\x04 \x03(\x0b\x32\r.ProtoChannel\x12\x1c\n\x14next_transmission_at\x18\x05 \x01(\r\x12\x17\n\x0ftransfer_reason\x18\x06 \x01(\r\x12\x0e\n\x06signal\x18\x07 \x01(\r\x12\x0c\n\x04hash\x18\t \x01(\r\x12\x13\n\x0b\x63loud_token\x18\x10 \x01(\tb\x06proto3'
  ,
  dependencies=[proto__measurement__types__pb2.DESCRIPTOR,])




_PROTOCHANNEL = _descriptor.Descriptor(
  name='ProtoChannel',
  full_name='ProtoChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ProtoChannel.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ProtoChannel.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_point', full_name='ProtoChannel.start_point', index=2,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_offsets', full_name='ProtoChannel.sample_offsets', index=3,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=192,
)


_PROTOMEASUREMENTS = _descriptor.Descriptor(
  name='ProtoMeasurements',
  full_name='ProtoMeasurements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial_num', full_name='ProtoMeasurements.serial_num', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_status', full_name='ProtoMeasurements.battery_status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurement_period_base', full_name='ProtoMeasurements.measurement_period_base', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurement_period_factor', full_name='ProtoMeasurements.measurement_period_factor', index=3,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channels', full_name='ProtoMeasurements.channels', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_transmission_at', full_name='ProtoMeasurements.next_transmission_at', index=5,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transfer_reason', full_name='ProtoMeasurements.transfer_reason', index=6,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signal', full_name='ProtoMeasurements.signal', index=7,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='ProtoMeasurements.hash', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_token', full_name='ProtoMeasurements.cloud_token', index=9,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=465,
)

_PROTOCHANNEL.fields_by_name['type'].enum_type = proto__measurement__types__pb2._MEASUREMENTTYPE
_PROTOMEASUREMENTS.fields_by_name['channels'].message_type = _PROTOCHANNEL
DESCRIPTOR.message_types_by_name['ProtoChannel'] = _PROTOCHANNEL
DESCRIPTOR.message_types_by_name['ProtoMeasurements'] = _PROTOMEASUREMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoChannel = _reflection.GeneratedProtocolMessageType('ProtoChannel', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCHANNEL,
  '__module__' : 'proto_measurements_pb2'
  # @@protoc_insertion_point(class_scope:ProtoChannel)
  })
_sym_db.RegisterMessage(ProtoChannel)

ProtoMeasurements = _reflection.GeneratedProtocolMessageType('ProtoMeasurements', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMEASUREMENTS,
  '__module__' : 'proto_measurements_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMeasurements)
  })
_sym_db.RegisterMessage(ProtoMeasurements)


_PROTOCHANNEL.fields_by_name['sample_offsets']._options = None
# @@protoc_insertion_point(module_scope)
