# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_cloud_token_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto_cloud_token_config.proto*\x9a\x01\n\x10\x43loudTokenConfig\x12\"\n\x1e\x43LOUD_TOKEN_CONFIG_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43LOUD_TOKEN_CONFIG_USER_SET\x10\x01\x12\x1f\n\x1b\x43LOUD_TOKEN_CONFIG_USE_IMEI\x10\x02\x12 \n\x1b\x43LOUD_TOKEN_CONFIG_NO_TOKEN\x10\xff\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_cloud_token_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOUDTOKENCONFIG._serialized_start=35
  _CLOUDTOKENCONFIG._serialized_end=189
# @@protoc_insertion_point(module_scope)
